routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name("home");
Route::view('/mail', 'mail.DofaRequest');
Route::view('/responseGoogle', "authGoogle");
Route::get('responseIntranet', 'Auth\LoginController@responseIntranet');

Route::get('login/google', 'Auth\LoginController@loginWithGoogle');
Route::get('login/google/callback', 'Auth\LoginController@googleCallback');

Route::middleware('auth')->get('/user', function (Request $request) {
    return \Illuminate\Support\Facades\Auth::user();
});

Route::middleware('auth')->resource('categoriesShopping', "CategoriesShoppingController")->names("categoriesShopping");
Route::middleware('auth')->get('providers/finish/{provider}', "ProvidersController@finalizar")->name("providers.finalizar");
Route::middleware('auth')->get('providers/rut/{provider}', "ProvidersController@rut")->name("providers.rut");
Route::middleware('auth')->get('providers/camara/{provider}', "ProvidersController@camara")->name("providers.camara");
Route::middleware('auth')->post('providers/updateFiles/{provider}', "ProvidersController@updateFiles")->name("providers.updateFiles");
Route::post('providers/updateFiles2/{provider}', "ProvidersController@updateFiles2")->name("providers.updateFiles2");
Route::get('updateFiles/{hash}', "ProvidersController@updateFilesLink")->name("providers.updateFiles.link");

Route::middleware('auth')->resource('providers', "ProvidersController")->names("providers");

Route::middleware('auth')->get('/quoteFinish/{quote}', "QuotesController@finishQuote")->name("finishQuote");
Route::middleware('auth')->get('/quotes', "QuotesController@index")->name("quotes.index");


Route::prefix("Dofa")->namespace("Dofa")->group(function (){
    Route::get("/", "Controller@index");
    Route::post("/", "Controller@finish");
    Route::post("/usersRequest", "Controller@usersRequest");
});

Route::prefix("budget")->namespace("Budget")->group(function (){
    Route::view("/add", "Budget.add");
    Route::get("/addNewActivity", "Controller@addNewActivity")->name("budget.addNewActivity");
    Route::post("/newActivityExtra", "Controller@newActivityExtra")->name("budget.newActivityExtra");
    Route::get("/transfer", "Controller@transfer")->name("budget.transfer");
    Route::post("/transfer", "Controller@transfer")->name("budget.transfer");
});

Route::get("/UnapprovedActivities", "UnapprovedActivities@index")->name("UnapprovedActivities");
Route::get('probando', 'BalancedScorecard\Controller@index');
Route::get('avatar/{user}', 'UserController@avatar');

app/CategoriesShopping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CategoriesShopping extends Model
{
    protected $table = "categories_shopping";
}

app/Http/Controllers/CategoriesShoppingController.php
<?php

namespace App\Http\Controllers;

use App\CategoriesShopping;
use App\Models\CenterCost;
use App\Models\RequestSupplies;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class CategoriesShoppingController extends Controller
{

    public function index(){
        $categories = CategoriesShopping::orderBy("name", "ASC")->paginate();
        return view("CategoriesShopping.index", compact("categories"));
    }

    public function json(Request $request){
        $page = $request->get("page", 1);
        $length = $request->get("length", 10);
        $find = $request->get("find", "");

        $response = CategoriesShopping::select("id", "name as text");

        if($request->has("find") && $find != ''){
            $response->where("name", "LIKE", "%$find%");
        }

        $response = $response->orderBy("name", "ASC")->paginate($length)->toArray();

        $data = $response;

        return response()->json($data);
    }

    public function create(){
        return view("CategoriesShopping.create");
    }

    public function store(Request $request){

        $categoria = new CategoriesShopping();
        $categoria->name = $request->name;
        $categoria->save();

        return redirect()->route("categoriesShopping.index")->with("success", collect(["Categoria creada con Exito"]));

    }

}

resources/views/CategoriesShopping/create.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-12">
                        <h3 class="title">Crear categoria <a href="{{ route("categoriesShopping.index") }}" class="btn btn-red float-right">Volver</a></h3>
                    </div>
                </div>
                <div class="card">
                    <div class="card-head pt-4">

                    </div>
                    <div class="card-body">
                        <form action="{{ route("categoriesShopping.store") }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-12">
                                    <div class="input-group">
                                        <input type="text" name="name" class="form-control" placeholder="Nombre de la categoria">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-red">Crear</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection

resources/views/CategoriesShopping/index.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-12">
                        <h3 class="title">Categorias <a href="{{ route("categoriesShopping.create") }}" class="btn btn-red float-right">Nueva categoria</a></h3>
                    </div>
                </div>
                <div class="card">
                    <div class="card-head pt-4">

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($categories as $category)
                                        <tr>
                                            <td>{{$category->name}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection