routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name("home");
Route::view('/mail', 'mail.DofaRequest');
Route::view('/responseGoogle', "authGoogle");
Route::get('responseIntranet', 'Auth\LoginController@responseIntranet');

Route::get('login/google', 'Auth\LoginController@loginWithGoogle');
Route::get('login/google/callback', 'Auth\LoginController@googleCallback');

Route::middleware('auth')->get('/user', function (Request $request) {
    return \Illuminate\Support\Facades\Auth::user();
});

Route::middleware('auth')->resource('categoriesShopping', "CategoriesShoppingController")->names("categoriesShopping");
Route::middleware('auth')->get('providers/finish/{provider}', "ProvidersController@finalizar")->name("providers.finalizar");
Route::middleware('auth')->get('providers/rut/{provider}', "ProvidersController@rut")->name("providers.rut");
Route::middleware('auth')->get('providers/camara/{provider}', "ProvidersController@camara")->name("providers.camara");
Route::middleware('auth')->post('providers/updateFiles/{provider}', "ProvidersController@updateFiles")->name("providers.updateFiles");
Route::post('providers/updateFiles2/{provider}', "ProvidersController@updateFiles2")->name("providers.updateFiles2");
Route::get('updateFiles/{hash}', "ProvidersController@updateFilesLink")->name("providers.updateFiles.link");

Route::middleware('auth')->resource('providers', "ProvidersController")->names("providers");

Route::middleware('auth')->get('/quoteFinish/{quote}', "QuotesController@finishQuote")->name("finishQuote");
Route::middleware('auth')->get('/quotes', "QuotesController@index")->name("quotes.index");


Route::prefix("Dofa")->namespace("Dofa")->group(function (){
    Route::get("/", "Controller@index");
    Route::post("/", "Controller@finish");
    Route::post("/usersRequest", "Controller@usersRequest");
});

Route::prefix("budget")->namespace("Budget")->group(function (){
    Route::view("/add", "Budget.add");
    Route::get("/addNewActivity", "Controller@addNewActivity")->name("budget.addNewActivity");
    Route::post("/newActivityExtra", "Controller@newActivityExtra")->name("budget.newActivityExtra");
    Route::get("/transfer", "Controller@transfer")->name("budget.transfer");
    Route::post("/transfer", "Controller@transfer")->name("budget.transfer");
});

Route::get("/UnapprovedActivities", "UnapprovedActivities@index")->name("UnapprovedActivities");
Route::get('probando', 'BalancedScorecard\Controller@index');
Route::get('avatar/{user}', 'UserController@avatar');

app/Provider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Provider extends Model
{

}

app/Http/Controllers/ProvidersController.php
<?php

namespace App\Http\Controllers;

use App\CategoriesShopping;
use App\Models\CenterCost;
use App\Models\RequestSupplies;
use App\Provider;
use App\Quote;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ProvidersController extends Controller
{

    public function index(){
        $providers = Provider::orderBy("created_at", "DESC")->paginate();
        return view("Providers.index", compact("providers"));
    }

    public function create(){

        return view("Providers.create");

    }

    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            "name" => "required",
            "email" => "required",
            "phone" => "required",
            "adviser" => "required"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        $provider = new Provider();
        $provider->name = $request->name;
        $provider->email = $request->email;
        $provider->phone = $request->phone;
        $provider->nit = $request->nit;
        $provider->adviser = $request->adviser;
        $provider->direccion = $request->direccion;
        $provider->city = $request->city;
        $provider->state = false;

        try{
            $provider->save();
        }catch (\Exception $e){
            $validate->errors()->add("error", $e->getMessage());
            return redirect()->back()->withErrors($validate)->withInput();
        }

        return redirect()->route("providers.index");

    }

    public function finalizar($provider){
        $provider = Provider::find($provider);
        return view("Providers.finish", compact("provider"));
    }

    public function rut($provider){
        $provider = Provider::find($provider);
        if(is_null($provider->rut)){
            return response("");
        }
        $file = Storage::get($provider->rut);
        $type = Storage::mimeType($provider->rut);
        return response()->make($file)->header('Content-Type', $type);
    }

    public function camara($provider){
        $provider = Provider::find($provider);
        if(is_null($provider->camara)){
            return response("");
        }
        $file = Storage::get($provider->camara);
        $type = Storage::mimeType($provider->camara);
        return response()->make($file)->header('Content-Type', $type);
    }

    public function updateFilesLink($hash){
        $provider = str_replace("proveedor-", "", base64_decode($hash));
        $provider = Provider::find($provider);
        return view("Providers.finishLink", compact("provider"));
    }

    public function updateFiles(Request $request, $provider){
        $validate = Validator::make($request->all(), [
            "rut" => "required|file|mimes:pdf",
            "camara" => "required|file|mimes:pdf"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }
        $provider = Provider::find($provider);

        try{
            $provider->rut = Storage::putFileAs('proveedores/' . $provider->id, $request->file("rut"), "rut.pdf");
        }catch (\Exception $e){
            $validate->errors()->add("rut", "No fue posible subir el archivo para RUT");
            return redirect()->back()->withErrors($validate)->withInput();
        }

        try{
            $provider->camara = Storage::putFileAs('proveedores/' . $provider->id, $request->file("camara"), "camara.pdf");
        }catch (\Exception $e){
            $validate->errors()->add("camara", "No fue posible subir el archivo para Camara de comercio");
            return redirect()->back()->withErrors($validate)->withInput();
        }

        $provider->state = true;
        try{
            $provider->save();
        }catch (\Exception $e){
            $validate->errors()->add("error", $e->getMessage());
            return redirect()->back()->withErrors($validate)->withInput();
        }

        return redirect()->route("providers.index");

    }

    public function updateFiles2(Request $request, $provider){
        $validate = Validator::make($request->all(), [
            "rut" => "required|file|mimes:pdf",
            "camara" => "required|file|mimes:pdf"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }
        $provider = Provider::find($provider);

        try{
            $provider->rut = Storage::putFileAs('proveedores/' . $provider->id, $request->file("rut"), "rut.pdf");
        }catch (\Exception $e){
            $validate->errors()->add("rut", "No fue posible subir el archivo para RUT");
            return redirect()->back()->withErrors($validate)->withInput();
        }

        try{
            $provider->camara = Storage::putFileAs('proveedores/' . $provider->id, $request->file("camara"), "camara.pdf");
        }catch (\Exception $e){
            $validate->errors()->add("camara", "No fue posible subir el archivo para Camara de comercio");
            return redirect()->back()->withErrors($validate)->withInput();
        }

        try{
            $provider->save();
        }catch (\Exception $e){
            $validate->errors()->add("error", $e->getMessage());
            return redirect()->back()->withErrors($validate)->withInput();
        }

        return view("providers.thanks", compact("provider"));

    }

    public function show($provider){
        $provider = Provider::find($provider);
        return view("Providers.show", compact("provider"));

    }

    public function update(Request $request, $provider){
        $validate = Validator::make($request->all(), [
            "name" => "required",
            "email" => "required",
            "phone" => "required",
            "adviser" => "required"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        $provider = Provider::find($provider);
        $provider->name = $request->name;
        $provider->email = $request->email;
        $provider->phone = $request->phone;
        $provider->nit = $request->nit;
        $provider->adviser = $request->adviser;
        $provider->direccion = $request->direccion;
        $provider->city = $request->city;

        try{
            $provider->save();
        }catch (\Exception $e){
            $validate->errors()->add("error", $e->getMessage());
            return redirect()->back()->withErrors($validate)->withInput();
        }

        return redirect()->route("providers.index");

    }

    public function listJson(Request $request){
        $page = $request->get("page", 1);
        $length = $request->get("length", 10);
        $find = $request->get("find", "");

        $response = Provider::select("id", "name as text");

        if($request->has("find") && $find != ''){
            $response->where("name", "LIKE", "%$find%");
        }

        $response = $response->orderBy("name", "ASC")->paginate($length)->toArray();

        $data = [
            "results" => $response["data"],
            "pagination" => [
                "more" => !is_null($response["next_page_url"])
            ]
        ];

        return response()->json($data);
    }

}

resources/views/Providers/create.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-9">
                        <h3 class="title">Nuevo proveedor</h3>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route("providers.store") }}" method="POST">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="name" class="form-control" placeholder="Nombre" required>
                                </div>
                                <div class="col-6">
                                    <input type="email" name="email" class="form-control" placeholder="Email" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="adviser" class="form-control" placeholder="Nombre contacto" required>
                                </div>
                                <div class="col-6">
                                    <input type="text" name="phone" class="form-control" placeholder="Teléfono" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="nit" class="form-control" placeholder="NIT">
                                </div>
                                <div class="col-6">
                                    <input type="text" name="direccion" class="form-control" placeholder="Dirección">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="city" class="form-control" placeholder="Ciudad">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12 text-right">
                                    <button type="submit" class="btn btn-red">
                                        Crear proveedor
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection

resources/views/Providers/finish.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-9">
                        <h3 class="title">{{ $provider->name }}</h3>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route("providers.updateFiles", $provider->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-6">
                                    <label for="rut">RUT</label>
                                    <label for="rutFile" data-type="upload" @if(!is_null($provider->rut)) data-file_name="<a target='_blank' href='/providers/rut/{{ $provider->id }}' >RUT</a>" @endif>
                                        <input type="file" id="rutFile" name="rut" accept="application/pdf" class="form-control" placeholder="Rut" required>
                                    </label>
                                </div>
                                <div class="col-6">
                                    <label for="camara">Camara de comercio</label>
                                    <label for="camaraFile"  data-type="upload" @if(!is_null($provider->camara)) data-file_name="<a target='_blank' href='/providers/camara/{{ $provider->id }}' >CAMARA</a>" @endif>
                                        <input type="file" id="camaraFile" name="camara" accept="application/pdf" class="form-control" placeholder="Camara de comercio" required>
                                    </label>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12 text-right">
                                    <button type="submit" class="btn btn-red">
                                        Subir documentos
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection

@section("script")
    <script src="{{ asset("js/uploadFile.js") }}"></script>
@endsection

resources/views/Providers/finishLink.blade.php
@extends("layouts.appSimple")
@section("content")
    <div class="container py-4">
        <div class="row">
            <div class="col-9">
                <h3 class="title">Bienvenido {{ $provider->name }}</h3>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <form action="{{ route("providers.updateFiles2", $provider->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <div class="col-6">
                            <label for="rut">RUT</label>
                            <input type="file" id="rut" name="rut" accept="application/pdf" class="form-control" placeholder="Rut" required>
                        </div>
                        <div class="col-6">
                            <label for="camara">Camara de comercio</label>
                            <input type="file" id="camara" name="camara" accept="application/pdf" class="form-control" placeholder="Camara de comercio" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12 text-right">
                            <button type="submit" class="btn btn-red">
                                Subir documentos
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Providers/index.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-9">
                        <h3 class="title">Proveedores</h3>
                    </div>
                    <div class="col text-right">
                        <a href="{{ route("providers.create") }}" class="btn btn-red">
                            Nuevo proveedor
                        </a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-head pt-4">

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Email</th>
                                    <th>Contacto</th>
                                    <th>Telefono</th>
                                    <th>Prospecto</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($providers as $provider)
                                    <tr>
                                        <td>{{ $provider->name }}</td>
                                        <td>{{ $provider->email }}</td>
                                        <td>{{ $provider->adviser }}</td>
                                        <td>{{ $provider->phone }}</td>
                                        <td>
                                            <div class="alert {{$provider->state ? "alert-success" : "alert-danger"}} text-center">
                                                {{ $provider->state ? "Proveedor" : "Prospecto" }}
                                            </div>
                                        </td>
                                        <td>
                                            <a href="{{ route("providers.finalizar", $provider->id) }}" class="btn btn-red w-100 mb-2">
                                                Documentos
                                            </a>
                                            <a href="{{ route("providers.show", $provider->id) }}" class="btn btn-red w-100">
                                                Editar
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection

resources/views/Providers/show.blade.php
@extends("layouts.app")
@section("content")
    <index>
        <template v-slot:content>
            <div class="container py-4">
                <div class="row">
                    <div class="col-9">
                        <h3 class="title">{{ $provider->name }}</h3>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route("providers.update", $provider->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="name" class="form-control" placeholder="Nombre" value="{{ $provider->name }}" required>
                                </div>
                                <div class="col-6">
                                    <input type="email" name="email" class="form-control" placeholder="Email" value="{{ $provider->email }}" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="adviser" class="form-control" placeholder="Nombre contacto" value="{{ $provider->adviser }}" required>
                                </div>
                                <div class="col-6">
                                    <input type="text" name="phone" class="form-control" placeholder="Teléfono" value="{{ $provider->phone }}" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="nit" class="form-control" placeholder="NIT" value="{{ $provider->nit }}">
                                </div>
                                <div class="col-6">
                                    <input type="text" name="direccion" class="form-control" placeholder="Dirección" value="{{ $provider->direccion }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <input type="text" name="city" class="form-control" placeholder="Ciudad"  value="{{ $provider->ciudad }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12 text-right">
                                    <button type="submit" class="btn btn-red">
                                        Editar proveedor
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </template>
    </index>
@endsection

resources/views/Providers/thanks.blade.php
@extends("layouts.appSimple")
@section("content")
    <div class="container py-4">
        <div class="row">
            <div class="col-9">
                <h3 class="title">Gracias {{ $provider->name }}</h3>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
               <h4>Muchas gracias por enviarnos tu documentación pronto nos contactaremos contigo</h4>
            </div>
        </div>
    </div>
@endsection